name: Docker CI/CD for Trades

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build & push with Cache
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/trades:latest, ${{ secrets.DOCKER_HUB_USERNAME }}/trades:0.0.2
          cache-from: type=registry,ref=${{secrets.DOCKER_HUB_USERNAME}}/trades:cache
          cache-to: type=registry,ref=${{secrets.DOCKER_HUB_USERNAME}}/trades:cache,mode=max
